services:
  # 1. Database
  mongodb:
    image: mongo:latest
    container_name: wanderlust_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - wanderlust_network

  # 2. Redis
  redis:
    image: redis:alpine
    container_name: wanderlust_redis
    restart: always
    networks:
      - wanderlust_network

  # 3. Backend
  backend:
    build: ./backend
    container_name: wanderlust_backend
    restart: always
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongodb
      - redis
    networks:
      - wanderlust_network

  # 4. Frontend
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_PATH=${VITE_API_PATH}
    container_name: wanderlust_frontend
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - backend
    networks:
      - wanderlust_network

networks:
  wanderlust_network:
    driver: bridge

volumes:
  mongo_data:
